FROM ubuntu:20.04

WORKDIR /organizer_server

COPY . /organizer_server/

RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip

RUN pip3 install .

EXPOSE 8001

CMD ["gunicorn", "--bind", "0.0.0.0:8001", "--workers", "32", "ssi_organizer:app"]
